"""
_dev/update_readmes.py
=======================
Auto-generates or updates table-of-contents sections in README files
for numbered exercise directories.

Usage:
    python _dev/update_readmes.py                     # Preview changes
    python _dev/update_readmes.py --write             # Apply changes
    python _dev/update_readmes.py --dir 01-core-python  # Single directory
"""

import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

TOC_HEADER = "## File Index"
TOC_TEMPLATE = """\
| # | File | Topic | Description |
|---|---|------|-------------|
%s

<!-- AUTO-GENERATED by update_readmes.py -- do not edit manually -->
"""


def extract_toc_info(dirpath: str, filename: str) -> tuple:
    """
    Extract file number, topic name, and description from a .py file.
    Returns (number, topic, description) or None.
    """
    filepath = os.path.join(dirpath, filename)
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read(500)  # Read first 500 chars
    except (UnicodeDecodeError, OSError):
        return None
    
    # Extract number from filename
    match = re.match(r"(\d{2})[- ](.+)\.py", filename)
    if not match:
        return None
    
    num = match.group(1)
    
    # Extract topic from docstring first line
    doc_match = re.search(r'""".*?\n(.*?)(?:\n|$)', content, re.DOTALL)
    if doc_match:
        topic = doc_match.group(1).strip().rstrip("=").strip()
    else:
        topic = match.group(2).replace("-", " ").title()
    
    # Extract description from second line
    desc_match = re.search(r'(?:Topics:|About:|Description:)\s*(.*?)$', content, re.MULTILINE)
    description = desc_match.group(1).strip() if desc_match else ""
    
    return (num, topic, description[:80])


def generate_toc(dirpath: str) -> str | None:
    """Generate a table of contents for all .py files in the directory."""
    files = sorted(f for f in os.listdir(dirpath) if re.match(r"\d{2}", f) and f.endswith(".py"))
    if not files:
        return None
    
    rows = []
    for filename in files:
        info = extract_toc_info(dirpath, filename)
        if info:
            num, topic, desc = info
            rows.append(f"| {num} | `{filename}` | {topic} | {desc} |")
    
    if not rows:
        return None
    
    return TOC_TEMPLATE % "\n".join(rows)


def update_readme(dirpath: str, write: bool = False) -> bool:
    """Update the README.md in the given directory with generated TOC."""
    readme = os.path.join(dirpath, "README.md")
    
    toc = generate_toc(dirpath)
    if not toc:
        return False
    
    # Read existing README
    if os.path.isfile(readme):
        with open(readme, "r", encoding="utf-8") as f:
            content = f.read()
    else:
        content = f"# {os.path.basename(dirpath)}\n\n"
    
    # Replace existing TOC section or append
    toc_section = f"{TOC_HEADER}\n\n{toc}"
    
    if TOC_HEADER in content:
        # Replace existing TOC
        pattern = re.compile(
            rf"{re.escape(TOC_HEADER)}.*?AUTO-GENERATED.*?-->",
            re.DOTALL
        )
        new_content = pattern.sub(toc_section, content)
    else:
        # Append before any final section
        new_content = content.rstrip() + "\n\n" + toc_section + "\n"
    
    if new_content == content:
        return False
    
    if write:
        with open(readme, "w", encoding="utf-8") as f:
            f.write(new_content)
        print(f"  ✏️  Updated: {os.path.relpath(readme, HERE)}")
    else:
        print(f"  📝 Would update: {os.path.relpath(readme, HERE)}")
    
    return True


def main():
    parser = argparse.ArgumentParser(
        description="Auto-generate README table of contents"
    )
    parser.add_argument("--write", action="store_true",
                        help="Actually write changes (default: preview)")
    parser.add_argument("--dir", type=str, default=None,
                        help="Process a single directory (relative to python root)")
    args = parser.parse_args()
    
    if args.dir:
        dirs = [os.path.join(HERE, args.dir)]
    else:
        # Find all numbered phase directories
        dirs = []
        for item in os.listdir(HERE):
            item_path = os.path.join(HERE, item)
            if os.path.isdir(item_path) and re.match(r"\d{2}-", item):
                dirs.append(item_path)
    
    updated = 0
    for d in dirs:
        if update_readme(d, write=args.write):
            updated += 1
    
    print(f"\n{'✅' if args.write else '📝'} {updated} README(s) would be updated.")
    if not args.write:
        print("Run with --write to apply changes.")
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
